<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>

    <AssemblyName>Flow.Launcher.Plugin.WindowsTasks</AssemblyName>
    <PackageId>Flow.Launcher.Plugin.WindowsTasks</PackageId>
    <Authors>TBM13</Authors>
    <PackageProjectUrl>https://github.com/TBM13/Flow.Launcher/tree/TBM13/Plugins/Flow.Launcher.Plugin.WindowsTasks</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TBM13/Flow.Launcher/tree/TBM13/Plugins/Flow.Launcher.Plugin.WindowsTasks</RepositoryUrl>
    <PackageTags>flow-launcher flow-plugin</PackageTags>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
    <PackageReference Include="TaskSchedulerEditor" Version="2.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Flow.Launcher.Plugin\Flow.Launcher.Plugin.csproj" />
  </ItemGroup>

</Project>
