<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>

    <StartupObject>Flow.Launcher.App.App</StartupObject>
    <ApplicationIcon>App\app.ico</ApplicationIcon>
    <ApplicationManifest>App\app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <PublishDir>..\Output\Publish\</PublishDir>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\SolutionAssemblyInfo.cs" Link="Properties\SolutionAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	  <Content Include="Images\*.ico">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Themes\*.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SegoeFluentIcons.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="18.7.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flow.Launcher.Core\Flow.Launcher.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <FLLUseDependencyInjection>true</FLLUseDependencyInjection>
  </PropertyGroup>

  <!-- Build flow.launcher.command on dotnet publish -->
  <Target Name="PublishFlowCommand" AfterTargets="Publish">
    <Exec Command="dotnet publish ..\Flow.Launcher.Command -c $(Configuration) -r $(RuntimeIdentifier)" />
  </Target>
 
</Project>