<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>

    <StartupObject>Flow.Launcher.App.App</StartupObject>
    <ApplicationIcon>App\app.ico</ApplicationIcon>
    <ApplicationManifest>App\app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <PublishDir>..\Output\Publish\</PublishDir>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\SolutionAssemblyInfo.cs" Link="Properties\SolutionAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	  <Content Include="Images\*.ico">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\SegoeFluentIcons.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-rc.1.26425.128" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flow.Launcher.Core\Flow.Launcher.Core.csproj" />
    <ProjectReference Include="..\Flow.Launcher.PluginSDK\Flow.Launcher.PluginSDK.csproj" />

    <ProjectReference Include="..\UI.WPF.Modern\source\iNKORE.UI.WPF.Modern\iNKORE.UI.WPF.Modern.csproj" />
    <ProjectReference Include="..\UI.WPF.Modern\source\iNKORE.UI.WPF.Modern.Controls\iNKORE.UI.WPF.Modern.Controls.csproj" />
  </ItemGroup>

  <!-- Build flow.launcher.command on dotnet publish -->
  <Target Name="PublishFlowCommand" AfterTargets="Publish">
    <Exec Command="dotnet publish ..\Flow.Launcher.Command -c $(Configuration) -r $(RuntimeIdentifier)" />
  </Target>
 
</Project>