<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <PublishDir>..\Output\Publish\Command\</PublishDir>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>portable</DebugType>
    <OutputPath>..\Output\Debug\Command\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
    <OutputPath>..\Output\Release\Command\</OutputPath>
  </PropertyGroup>

</Project>