<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net11.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>

		<NeutralLanguage>en-US</NeutralLanguage>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>

    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);GetDocumentationFile</TargetsForTfmSpecificBuildOutput>
		<ApplicationIcon>..\..\assets\icons\WpfLibrary.ico</ApplicationIcon>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>..\..\assets\others\iNKORE.Pulic.snk</AssemblyOriginatorKeyFile>
		<RootNamespace>iNKORE.UI.WPF.Modern</RootNamespace>
		<NoWarn>$(NoWarn);CS1591;1701;1702;CA1416;CS1573</NoWarn>
	</PropertyGroup>

	<!--<PropertyGroup>
		<CsWinRTEmbedded>true</CsWinRTEmbedded>
		<CsWinRTWindowsMetadata>10.0.18362.0</CsWinRTWindowsMetadata>
		<CsWinRTIncludes>
			Windows.Foundation;
			Windows.UI.Color;
			Windows.UI.IColors;
			Windows.UI.ViewManagement.HandPreference;
			Windows.UI.ViewManagement.IUISettings;
			Windows.UI.ViewManagement.UIColorType;
			Windows.UI.ViewManagement.UIElementType;
			Windows.UI.ViewManagement.UISettings;
		</CsWinRTIncludes>
		<CsWinRTExcludes>
			Windows.Foundation.Diagnostics;
			Windows.Foundation.PropertyType;
		</CsWinRTExcludes>
	</PropertyGroup>-->

	<ItemGroup>
	  <Compile Include="..\iNKORE.UI.WPF.Modern\Properties\AssemblyInfoCommon.cs" Link="Properties\AssemblyInfoCommon.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\iNKORE.UI.WPF.Modern\iNKORE.UI.WPF.Modern.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="iNKORE.UI.WPF.Modern.Controls.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
