<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net11.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>disable</Nullable>

		<NeutralLanguage>en-US</NeutralLanguage>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>

    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <NoWarn>1701;1702;1573;1591;CA1416</NoWarn>
		<ApplicationIcon>..\..\assets\icons\WpfLibrary.ico</ApplicationIcon>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>..\..\assets\others\iNKORE.Pulic.snk</AssemblyOriginatorKeyFile>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<NoWarn>$(NoWarn);CS1591;1701;1702;CA1416;CS8632</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Common\VisualStates\**" />
	  <EmbeddedResource Remove="Common\VisualStates\**" />
	  <None Remove="Common\VisualStates\**" />
	  <Page Remove="Common\VisualStates\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Controls\SimpleStackPanel.cs" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="iNKORE.UI.WPF.Modern.Controls" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Fonts\FluentSystemIcons-Filled.ttf" />
		<None Remove="Resources\Fonts\FluentSystemIcons-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="..\..\assets\icons\WpfLibrary_256w.png" Link="Resources\Images\WpfLibrary_256w.png" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="..\..\assets\images\banners\UI.WPF.Modern_Main_1280w.png" Link="Resources\Images\UI.WPF.Modern_Main_1280w.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\Fonts\FluentSystemIcons-Filled.ttf" />
		<Resource Include="Resources\Fonts\FluentSystemIcons-Regular.ttf" />
		<Resource Include="Resources\Images\NoiseAsset_256X256_PNG.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Strings\Strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Strings\Strings.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
			<CustomToolNamespace>iNKORE.UI.WPF.Modern</CustomToolNamespace>
		</EmbeddedResource>
	</ItemGroup>

</Project>
