<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <UseWpf>true</UseWpf>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Flow.Launcher.Core</RootNamespace>
    <AssemblyName>Flow.Launcher.Core</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\Output\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\Output\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
    <NoWarn>$(NoWarn);FLSG0007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Plugin\README.md" />
    <None Include="README.md" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="FodyWeavers.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\SolutionAssemblyInfo.cs" Link="Properties\SolutionAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="FodyWeavers.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Flow.Launcher.Localization" Version="0.0.6" />
    <PackageReference Include="Meziantou.Framework.Win32.Jobs" Version="3.4.12" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageReference Include="StreamJsonRpc" Version="2.22.23" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <FLLUseDependencyInjection>true</FLLUseDependencyInjection>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Remove="Languages\en.xaml" />
    <AdditionalFiles Include="..\Flow.Launcher\Languages\en.xaml">
      <Link>Languages\en.xaml</Link>
    </AdditionalFiles>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flow.Launcher.Infrastructure\Flow.Launcher.Infrastructure.csproj" />
    <ProjectReference Include="..\Flow.Launcher.Plugin\Flow.Launcher.Plugin.csproj" />
  </ItemGroup>

</Project>