<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWpf>true</UseWpf>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Flow.Launcher.Core</RootNamespace>
    <AssemblyName>Flow.Launcher.Core</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\Output\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\Output\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
    <NoWarn>$(NoWarn);FLSG0007</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="FodyWeavers.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\SolutionAssemblyInfo.cs" Link="Properties\SolutionAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="FodyWeavers.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Flow.Launcher.Localization" Version="0.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <FLLUseDependencyInjection>true</FLLUseDependencyInjection>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Remove="Languages\en.xaml" />
    <AdditionalFiles Include="..\Flow.Launcher\Languages\en.xaml">
      <Link>Languages\en.xaml</Link>
    </AdditionalFiles>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flow.Launcher.Infrastructure\Flow.Launcher.Infrastructure.csproj" />
    <ProjectReference Include="..\Flow.Launcher.Plugin\Flow.Launcher.Plugin.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.Calculator\Flow.Launcher.Plugin.Calculator.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.Explorer\Flow.Launcher.Plugin.Explorer.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.PluginIndicator\Flow.Launcher.Plugin.PluginIndicator.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.ProcessKiller\Flow.Launcher.Plugin.ProcessKiller.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.Program\Flow.Launcher.Plugin.Program.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.Sys\Flow.Launcher.Plugin.Sys.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.WindowsServices\Flow.Launcher.Plugin.WindowsServices.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.WindowsSettings\Flow.Launcher.Plugin.WindowsSettings.csproj" />
    <ProjectReference Include="..\Plugins\Flow.Launcher.Plugin.WindowsTasks\Flow.Launcher.Plugin.WindowsTasks.csproj" />
  </ItemGroup>

</Project>