<Project>
  <PropertyGroup Condition="'$(PackageId)' != ''">
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/InkoreStudios/UI.WPF.Modern</PackageProjectUrl>
    <PackageTags>WPF XAML UI Theme Controls Fluent Modern Metro WinUI</PackageTags>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>True</Optimize>
  </PropertyGroup>
</Project>
